# Generated by Django 5.2.8 on 2025-11-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('Transactions_type', models.CharField(choices=[('CREDIT', 'credit'), ('DEBIT', 'debit')], max_length=100)),
            ],
        ),
    ]
