# Generated by Django 5.2.8 on 2025-11-26 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('admitted_on', models.DateField(auto_now_add=True)),
                ('discharged_on', models.DateField(blank=True, null=True)),
                ('is_discharged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-admitted_on'],
            },
        ),
    ]
